from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def _fmt(value: Any) -> str:
    if isinstance(value, float):
        return f"{value:.6f}"
    return str(value)


def write_stage_report(
    output_dir: str | Path,
    title: str,
    sections: list[tuple[str, dict[str, Any]]],
    filename: str = "v2_stage_report.md",
) -> Path:
    output = Path(output_dir)
    output.mkdir(parents=True, exist_ok=True)
    lines = [f"# {title}", "", "Generated by the Venus / Magellan V2 pipeline.", ""]
    for heading, payload in sections:
        lines.extend([f"## {heading}", ""])
        for key, value in payload.items():
            lines.append(f"- **{key}**: {_fmt(value)}")
        lines.append("")
    path = output / filename
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def write_json(path: str | Path, payload: dict[str, Any]) -> Path:
    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(payload, indent=2, default=str) + "\n", encoding="utf-8")
    return out
