"""Source inventory for the Venus / Magellan project."""

PROVIDED_SOURCE_FILES = [
    "src/inspection/inspect_geology.py",
    "src/inspection/inspect_guinevere_gdb.py",
    "src/inspection/inspect_rasters.py",
    "src/modeling/analyze_features.py",
    "src/modeling/compare_kmeans_gmm_k4.py",
    "src/modeling/dbscan_analysis.py",
    "src/modeling/dbscan_compare.py",
    "src/modeling/evaluate_k.py",
    "src/modeling/feature_diagnostics.py",
    "src/modeling/gmm_model_k4.py",
    "src/modeling/hierarchical_clustering.py",
    "src/modeling/kmeans_model_k4.py",
    "src/modeling/kmeans_stability.py",
    "src/modeling/predict_full_map_k4.py",
    "src/spatial/cluster_area_statistics_k4.py",
    "src/spatial/global_cluster_characterization.py",
    "src/spatial/spatial_analysis_k4.py",
    "src/spatial/spatial_smoothing_k4_chunked.py",
    "src/validation/cross_region_validation.py",
    "src/validation/final_geological_validation.py",
    "src/validation/geology_overlay_check.py",
    "src/validation/geology_reverse_validation.py",
    "src/validation/geology_validation_metrics.py",
    "src/validation/global_regional_geology_validation.py",
    "src/validation/guinevere_overlay_check.py",
    "src/validation/guinevere_usgs_polygon_validation.py",
    "src/validation/lada_usgs_polygon_validation.py",
    "src/validation/ovda_cluster_statistics.py",
    "src/validation/systematic_geological_validation.py",
    "src/validation/validate_geology.py",
    "src/validation/validate_ovda.py",
    "src/visualization/analyze_clusters_v3.py",
    "src/visualization/visualize_full_map_k4.py",
    "src/visualization/visualize_k4_geographic.py",
]
